[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "pypassplex"
version = "0.9.0"
description = ""
readme = "README.md"
requires-python = ">=3.8"
dependencies = []
authors = [{ name = "LukeS-05" }]

[tool.hatch.build.targets.wheel]
packages = ["src/pypassplex"]

[tool.hatch.build.targets.wheel.sources]
"src" = ""

[tool.hatch.build.targets.wheel.force-include]
"src/pypassplex/eff-words.txt" = "pypassplex/eff-words.txt"

[project.scripts]
ppxdemo-passgen = "pypassplex.demos.passgen:main"
ppxdemo-phrasegen = "pypassplex.demos.phrasegen:main"
ppxm = "pypassplex.ppxm.ppxm:main"